/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIdRouteImport } from './routes/pro.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as BookServiceIdRouteImport } from './routes/book.$serviceId'
import { Route as BookingsIdReviewRouteImport } from './routes/bookings.$id.review'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIdRoute = ProIdRouteImport.update({
  id: '/pro/$id',
  path: '/pro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingsRoute,
} as any)
const BookServiceIdRoute = BookServiceIdRouteImport.update({
  id: '/book/$serviceId',
  path: '/book/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdReviewRoute = BookingsIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BookingsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/pro/$id': typeof ProIdRoute
  '/bookings/$id/review': typeof BookingsIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/pro/$id': typeof ProIdRoute
  '/bookings/$id/review': typeof BookingsIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/pro/$id': typeof ProIdRoute
  '/bookings/$id/review': typeof BookingsIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/concierge'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/wallet'
    | '/welcome'
    | '/book/$serviceId'
    | '/bookings/$id'
    | '/category/$slug'
    | '/pro/$id'
    | '/bookings/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/concierge'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/wallet'
    | '/welcome'
    | '/book/$serviceId'
    | '/bookings/$id'
    | '/category/$slug'
    | '/pro/$id'
    | '/bookings/$id/review'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/concierge'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/wallet'
    | '/welcome'
    | '/book/$serviceId'
    | '/bookings/$id'
    | '/category/$slug'
    | '/pro/$id'
    | '/bookings/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  ConciergeRoute: typeof ConciergeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  BookServiceIdRoute: typeof BookServiceIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProIdRoute: typeof ProIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$id': {
      id: '/pro/$id'
      path: '/pro/$id'
      fullPath: '/pro/$id'
      preLoaderRoute: typeof ProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/book/$serviceId': {
      id: '/book/$serviceId'
      path: '/book/$serviceId'
      fullPath: '/book/$serviceId'
      preLoaderRoute: typeof BookServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/review': {
      id: '/bookings/$id/review'
      path: '/review'
      fullPath: '/bookings/$id/review'
      preLoaderRoute: typeof BookingsIdReviewRouteImport
      parentRoute: typeof BookingsIdRoute
    }
  }
}

interface BookingsIdRouteChildren {
  BookingsIdReviewRoute: typeof BookingsIdReviewRoute
}

const BookingsIdRouteChildren: BookingsIdRouteChildren = {
  BookingsIdReviewRoute: BookingsIdReviewRoute,
}

const BookingsIdRouteWithChildren = BookingsIdRoute._addFileChildren(
  BookingsIdRouteChildren,
)

interface BookingsRouteChildren {
  BookingsIdRoute: typeof BookingsIdRouteWithChildren
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsIdRoute: BookingsIdRouteWithChildren,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRouteWithChildren,
  ConciergeRoute: ConciergeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  BookServiceIdRoute: BookServiceIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProIdRoute: ProIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
