// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eanopvtsnrqqnkkdkhvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhbm9wdnRzbnJxcW5ra2RraHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3MDM2NTksImV4cCI6MjA5NDI3OTY1OX0.DFY5sraU4shADld-r98tIl36-pc6SJkv2Kvhc0dYZiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});